"""migration nullables

Revision ID: fd1d74e1aab2
Revises: b42e1c034026
Create Date: 2025-03-16 10:14:02.985250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd1d74e1aab2'
down_revision = 'b42e1c034026'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('observation',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('sub_categories', schema=None) as batch_op:
        batch_op.alter_column('observation',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sub_categories', schema=None) as batch_op:
        batch_op.alter_column('observation',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('observation',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
